const { parse, serialize, expandVariables } = require('../src/lib/parser');

describe('parser', () => {
  describe('parse', () => {
    it('should parse simple key=value pairs', () => {
      const result = parse('FOO=bar\nBAZ=qux');
      expect(result).toEqual({ FOO: 'bar', BAZ: 'qux' });
    });

    it('should skip comments and empty lines', () => {
      const result = parse('# comment\n\nFOO=bar\n// another comment');
      expect(result).toEqual({ FOO: 'bar' });
    });

    it('should handle double-quoted values', () => {
      const result = parse('MSG="hello world"');
      expect(result.MSG).toBe('hello world');
    });

    it('should handle single-quoted values', () => {
      const result = parse("MSG='hello world'");
      expect(result.MSG).toBe('hello world');
    });

    it('should handle values with equals signs', () => {
      const result = parse('URL=postgres://user:pass@host:5432/db?ssl=true');
      expect(result.URL).toBe('postgres://user:pass@host:5432/db?ssl=true');
    });

    it('should handle export prefix', () => {
      const result = parse('export FOO=bar');
      expect(result.FOO).toBe('bar');
    });

    it('should strip inline comments from unquoted values', () => {
      const result = parse('FOO=bar # this is a comment');
      expect(result.FOO).toBe('bar');
    });

    it('should not strip # inside quoted values', () => {
      const result = parse('FOO="bar # not a comment"');
      expect(result.FOO).toBe('bar # not a comment');
    });

    it('should handle empty values', () => {
      const result = parse('EMPTY=');
      expect(result.EMPTY).toBe('');
    });
  });

  describe('expandVariables', () => {
    it('should expand ${VAR} references', () => {
      const parsed = { HOST: 'localhost', URL: 'http://${HOST}:3000' };
      expandVariables(parsed);
      expect(parsed.URL).toBe('http://localhost:3000');
    });

    it('should handle nested expansion', () => {
      const parsed = { A: 'hello', B: '${A}', C: '${B} world' };
      expandVariables(parsed);
      expect(parsed.C).toBe('hello world');
    });
  });

  describe('serialize', () => {
    it('should serialize key-value pairs', () => {
      const result = serialize({ FOO: 'bar', BAZ: 'qux' });
      expect(result).toBe('FOO=bar\nBAZ=qux\n');
    });

    it('should quote values with spaces', () => {
      const result = serialize({ MSG: 'hello world' });
      expect(result).toBe('MSG="hello world"\n');
    });

    it('should add a header comment', () => {
      const result = serialize({ FOO: 'bar' }, { header: 'Generated by env-shield' });
      expect(result).toContain('# Generated by env-shield');
    });
  });
});
